function [fitresult, gof] = createFit_Fy(RPM, Fy)
%CREATEFIT(RPM,FY)
%  Create a fit.
%
%  Data for 'Fy_centered_2' fit:
%      X Input : RPM
%      Y Output: Fy
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 28-Oct-2019 09:14:58


%% Fit: 'Fy_centered_2'.
[xData, yData] = prepareCurveData( RPM, Fy );

% Set up fittype and options.
ft = fittype( 'poly5' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'Fy_centered_2' );
h = plot( fitresult, xData, yData );
legend( h, 'Fy vs. RPM', 'Fy_centered_2', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'RPM', 'Interpreter', 'none' );
ylabel( 'Fy', 'Interpreter', 'none' );
grid on


