function [fitresult, gof] = createFit_Fr(RPM, Fr)
%CREATEFIT(RPM,FR)
%  Create a fit.
%
%  Data for 'Fr_centered_2' fit:
%      X Input : RPM
%      Y Output: Fr
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 28-Oct-2019 09:10:16


%% Fit: 'Fr_centered_2'.
[xData, yData] = prepareCurveData( RPM, Fr );

% Set up fittype and options.
ft = fittype( 'poly2' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Normalize = 'on';
opts.Robust = 'Bisquare';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Fr_centered_2' );
h = plot( fitresult, xData, yData );
legend( h, 'Fr vs. RPM', 'Fr_centered_2', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'RPM', 'Interpreter', 'none' );
ylabel( 'Fr', 'Interpreter', 'none' );
grid on


