function [fitresult, gof] = createFit_cubic_interp(RPM_comb, plotdata)
%CREATEFIT1(RPM_COMB,PLOTDATA)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : RPM_comb
%      Y Output: plotdata
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 28-Oct-2019 15:58:07


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( RPM_comb, plotdata );

% Set up fittype and options.
ft = 'splineinterp';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', ' убическа€ интерпол€ци€' );
h = plot( fitresult, xData, yData );
legend( h, 'plotdata vs. RPM', ' убическа€ интерпол€ци€', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'RPM_comb', 'Interpreter', 'none' );
ylabel( 'plotdata', 'Interpreter', 'none' );
grid on


