function [fitresult, gof] = createFit_Mr(RPM, Mr)
%CREATEFIT1(RPM,MR)
%  Create a fit.
%
%  Data for 'Fz_centered_2' fit:
%      X Input : RPM
%      Y Output: Mr
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 28-Oct-2019 09:22:10


%% Fit: 'Fz_centered_2'.
[xData, yData] = prepareCurveData( RPM, Mr );

% Set up fittype and options.
ft = fittype( 'poly5' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'Fz_centered_2' );
h = plot( fitresult, xData, yData );
legend( h, 'Mr vs. RPM', 'Fz_centered_2', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'RPM', 'Interpreter', 'none' );
ylabel( 'Mr', 'Interpreter', 'none' );
grid on


