function [fitresult, gof] = createFit_poly_vs_cubic(RPM_comb, plotdata)
%CREATEFIT1(RPM_COMB,PLOTDATA)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : RPM_comb
%      Y Output: plotdata 
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 28-Oct-2019 15:57:45


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( RPM_comb, plotdata );

% Set up fittype and options.
ft = fittype( 'poly5' );
ft1 = 'splineinterp';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );
[fitresult1, gof1] = fit( xData, yData, ft1, 'Normalize', 'on' );


% Plot fit with data.
figure( 'Name', 'Полином 5ой степени' );
hold on
h = plot( fitresult,'b', xData, yData,'g*' );
h1 = plot( fitresult1,'r', xData,yData,'g*' );
legend( {'Исх. данные','Полином 5ой степени','Исх. данные', 'Кубическая интерполяция'}, 'Location', 'NorthEast', 'Interpreter', 'none' );
hold off
% Label axes
xlabel( 'RPM', 'Interpreter', 'none' );
ylabel( 'plotdata (F/M)', 'Interpreter', 'none' );
grid on


