function [fitresult, gof] = Cubic_Interp(X, Y, F_tr)
%CREATEFIT1(X,Y,F_TR)
%  Create a fit.
%
%  Data for 'Cubic_Interp' fit:
%      X Input : X
%      Y Input : Y
%      Z Output: F_tr
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 30-Nov-2019 07:57:31


%% Fit: 'Cubic_Interp'.
[xData, yData, zData] = prepareSurfaceData( X, Y, F_tr );

% Set up fittype and options.
ft = 'cubicinterp';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'Cubic_Interp' );
h = plot( fitresult, [xData, yData], zData );
title('Кубическая интерполяция');
legend( h, 'Cubic_Interp', 'F  vs. Q, RPM', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Q, л/мин', 'Interpreter', 'none' );
ylabel( 'RPM', 'Interpreter', 'none' );
zlabel( 'F, Н', 'Interpreter', 'none' );
grid on
view( -9.8, 17.4 );


