function [fitresult, gof] = createFit1(AorticTime, AorticPressure)
%CREATEFIT1(AORTICTIME,AORTICPRESSURE)
%  Create a fit.
%
%  Data for 'FourierFit' fit:
%      X Input : AorticTime
%      Y Output: AorticPressure
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 27-Apr-2020 18:13:06


%% Fit: 'FourierFit'.
[xData, yData] = prepareCurveData( AorticTime, AorticPressure );

% Set up fittype and options.
ft = fittype( 'fourier5' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
% opts.Normalize  = 'on';
opts.StartPoint = [0 0 0 0 0 0 0 0 0 0 0 0.00851957329787062];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'FourierFit_12pts' );
h = plot( fitresult, xData, yData );
legend( h, '\DeltaP vs. T', 'FourierFit 12 pts', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'T, לס', 'Interpreter', 'none' );
ylabel( '\DeltaP, לל נע.סע.', 'Interpreter', 'none' );
grid on



