function [fitresult, gof] = PolynomialFit55(X, Y, F_tr, ForM)
%CREATEFIT1(X,Y,F_TR)
%  Create a fit.
%
%  Data for 'PolynomialFit55' fit:
%      X Input : X
%      Y Input : Y
%      Z Output: F_tr
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 30-Nov-2019 10:11:52


%% Fit: 'PolynomialFit55'.
[xData, yData, zData] = prepareSurfaceData( X, Y, F_tr );

% Set up fittype and options.
ft = fittype( 'poly55' );
% opts = fitoptions( 'Method', 'LinearLeastSquares' );
% opts.Robust = 'LAR';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'Полином 5 степени' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'Polynomial Fit', 'F vs. Q, RPM', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Q', 'Interpreter', 'none' );
ylabel( 'RPM', 'Interpreter', 'none' );
if ForM == 0
    zlabel( 'F, Н', 'Interpreter', 'none' );
else
    zlabel( 'M, Н*m', 'Interpreter', 'none' );
end
grid on
% view( 2.6, 36.5 );
view( -9.8, 17.4 );

