function [fitresult, gof] = AorticFit(AorticTime, AorticPressure)
%CREATEFIT1(AORTICTIME,AORTICPRESSURE)
%  Create a fit.
%
%  Data for 'AorticFit' fit:
%      X Input : AorticTime
%      Y Output: AorticPressure
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Apr-2020 20:01:19


%% Fit: 'AorticFit'.
[xData, yData] = prepareCurveData( AorticTime, AorticPressure );

% Set up fittype and options.
ft = fittype( 'sin7' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf];
opts.StartPoint = [158.786695384126 0.00433323124633075 0.00185562787258809 52.678684624478 0.0086664624926615 1.42016017311076 12.3838898870769 0.017332924985323 2.28149002253031 9.13933515814893 0.0259993874779845 1.75035755998418 5.54995718089979 0.034665849970646 1.40825806538702 3.34615943647426 0.0433323124633075 1.07764798935895 1.39593074303513 0.0606652374486305 1.96038223940972];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'AorticFit' );
h = plot( fitresult, xData, yData );
legend( h, 'AorticPressure vs. AorticTime', 'AorticFit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'AorticTime', 'Interpreter', 'none' );
ylabel( 'AorticPressure', 'Interpreter', 'none' );
grid on


