function [fitresult, gof] = FourierFit5Normalized(AorticTime, AorticPressure)
%CREATEFIT1(AORTICTIME,AORTICPRESSURE)
%  Create a fit.
%
%  Data for 'FourierFit5Normalized' fit:
%      X Input : AorticTime
%      Y Output: AorticPressure
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 13-May-2020 16:22:23


%% Fit: 'FourierFit5Normalized'.
[xData, yData] = prepareCurveData( AorticTime, AorticPressure );

% Set up fittype and options.
ft = fittype( 'fourier5' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Normalize = 'on';
opts.StartPoint = [0 0 0 0 0 0 0 0 0 0 0 3.72433030374811];
xData=xData/1000; %ѕеревод мс в с
yData = yData*133.3224; %ѕеревод мм рт ст в ѕа
% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'ћетод ‘урье по 12 точкам' );
h = plot( fitresult, xData, yData );
legend( h, '–еальна€ запись', 'ћетод ‘урье по 12 точкам', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 't, с', 'Interpreter', 'none' );
ylabel( 'DeltaP, ѕа', 'Interpreter', 'none' );
grid on


